# Shared path contract for Omarchy and the Arch port.
#
# Stock Omarchy behavior is preserved when OMARCHY_*_HOME variables are
# unset. The Arch port sets them only inside its dedicated session.

: "${OMARCHY_SESSION_CONFIG_HOME:=${XDG_CONFIG_HOME:-$HOME/.config}}"
: "${OMARCHY_SESSION_STATE_HOME:=${XDG_STATE_HOME:-$HOME/.local/state}}"
: "${OMARCHY_SESSION_CACHE_HOME:=${XDG_CACHE_HOME:-$HOME/.cache}}"
: "${OMARCHY_SESSION_DATA_HOME:=${XDG_DATA_HOME:-$HOME/.local/share}}"

: "${OMARCHY_CONFIG_HOME:=$OMARCHY_SESSION_CONFIG_HOME/omarchy}"
: "${OMARCHY_STATE_HOME:=$OMARCHY_SESSION_STATE_HOME/omarchy}"
: "${OMARCHY_CACHE_HOME:=$OMARCHY_SESSION_CACHE_HOME/omarchy}"
: "${OMARCHY_DATA_HOME:=$OMARCHY_SESSION_DATA_HOME/omarchy}"

export \
  OMARCHY_SESSION_CONFIG_HOME \
  OMARCHY_SESSION_STATE_HOME \
  OMARCHY_SESSION_CACHE_HOME \
  OMARCHY_SESSION_DATA_HOME \
  OMARCHY_CONFIG_HOME \
  OMARCHY_STATE_HOME \
  OMARCHY_CACHE_HOME \
  OMARCHY_DATA_HOME
